apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: netbox
