apiVersion: v1
kind: Secret
metadata:
  name: netbox-secret
  labels:
    app: netbox
    component: application
type: Opaque
stringData:
  SECRET_KEY: RP1cwEWl-FJlxzUyxgSDLKuD3YMjpQSGPLkmhqDAJANy6Olfq2oQWiBUhcfVjh6g_ao
  SUPERUSER_PASSWORD: Netbox123!  # Change this in production
  SUPERUSER_API_TOKEN: 0123456789abcdef0123456789abcdef01234567  # Change this in production
